package com.aigen.sims.mining;

import java.util.*;
import java.util.regex.*;

/**
 * RepoWatcher — Watches a list of repos for new patterns.
 * Each repo is anchored to a hex coordinate for FOW-gated mining.
 * Tracks pending suggestions that need model voting.
 */
public class RepoWatcher {
    public static class WatchedRepo {
        public final String name;
        public final String path;
        public final String hexKey;       // FOW anchor hex for this repo
        public final String[] fileExts;   // which file extensions to scan
        public long lastScanned;
        public int pendingCount;

        public WatchedRepo(String name, String path, String hex, String... exts) {
            this.name = name; this.path = path; this.hexKey = hex;
            this.fileExts = exts.length > 0 ? exts : new String[]{".java", ".py", ".sh"};
        }
    }

    private final List<WatchedRepo> repos = new ArrayList<>();
    private final List<PatternMatch> pendingSuggestions = new ArrayList<>();
    private int totalPatternsFound;

    /** Register a repo to watch */
    public WatchedRepo addRepo(String name, String path, String hex, String... exts) {
        WatchedRepo r = new WatchedRepo(name, path, hex, exts);
        repos.add(r);
        return r;
    }

    /** Add a pending suggestion (from scanning or model-generated) */
    public void addSuggestion(PatternMatch pm) {
        if (pm.isActionable()) pendingSuggestions.add(pm);
    }

    /** Get pending suggestions and clear the queue */
    public List<PatternMatch> drainSuggestions() {
        List<PatternMatch> copy = new ArrayList<>(pendingSuggestions);
        pendingSuggestions.clear();
        return copy;
    }

    /** Run a scan: regex-match known patterns across watched repos (simulated here) */
    public List<PatternMatch> scan(PatternMatcher matcher) {
        List<PatternMatch> found = new ArrayList<>();
        for (WatchedRepo r : repos) {
            // Simulate scanning: each repo yields 1-3 patterns based on its name
            found.addAll(matcher.matchRepo(r));
            totalPatternsFound += found.size();
            r.lastScanned = System.currentTimeMillis();
        }
        // Add actionable ones as suggestions
        for (PatternMatch pm : found) addSuggestion(pm);
        return found;
    }

    /** Simulate model-generated code suggestions for a given repo */
    public List<PatternMatch> modelSuggest(String modelName, String repoName, String prompt) {
        List<PatternMatch> suggestions = new ArrayList<>();
        WatchedRepo r = repos.stream().filter(x -> x.name.equals(repoName)).findFirst().orElse(null);
        if (r == null) return suggestions;

        // Model "generates" pattern suggestions based on prompt
        String[] types = {"function", "class", "import"};
        String[] sigs = {
            "auto_" + prompt.replaceAll("[^a-z]", "_").substring(0, Math.min(15, prompt.length())),
            prompt.substring(0, Math.min(10, prompt.length())) + "Factory",
            "import " + repoName.toLowerCase().replaceAll("[^a-z]", ".") + ".*"
        };
        for (int i = 0; i < 3; i++) {
            PatternMatch pm = new PatternMatch(
                r.name, r.path + "/src/Generated.java", types[i % 3],
                sigs[i], "// Auto-generated by " + modelName, i + 1, 0.7 + i * 0.05, r.hexKey);
            suggestions.add(pm);
            addSuggestion(pm);
        }
        return suggestions;
    }

    public List<WatchedRepo> getRepos() { return Collections.unmodifiableList(repos); }
    public List<PatternMatch> getPending() { return Collections.unmodifiableList(pendingSuggestions); }
    public int pendingCount() { return pendingSuggestions.size(); }
    public int totalPatternsFound() { return totalPatternsFound; }

    @Override public String toString() {
        StringBuilder sb = new StringBuilder("RepoWatcher: " + repos.size() + " repos, " + pendingSuggestions.size() + " pending\n");
        for (WatchedRepo r : repos) sb.append("  ").append(r.name).append(" @ ⬡(").append(r.hexKey).append(")\n");
        return sb.toString();
    }
}
